cache: bundler

language: ruby

rvm:
  - 2.6
  - 2.7
  - 3.0
  - 3.1
  - 3.2
  - jruby-head
  - ruby-head

sudo: false

bundler_args: --without development --retry=3 --jobs=3

env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
